[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "GDdxxaxSUZMU2jkRcAxXcx15mjUeKtGJUag2bg1XD884"
voting = "BuNqj2CksTP9QwbYBhgC9DhHLbtnru2x8uSyumWRuEeq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
